name: Deploy master
on:
  push:
    branches:
      - master

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      # After calling google's auth `firebase deploy` will use this auth
      - name: Authenticate to Google Cloud/Firebase
        uses: google-github-actions/auth@v0.4.0
        with: 
          # This is the service account secret stored in github secrets (setup by `firebase init hosting:github`)
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KWBLOG_1C958 }}'
      - name: Deploy
        shell: pwsh
        run: |
          .\build.ps1 deploy